
# Paths.
data_dir:    ./_data
collections:    null

# Handling reading.
exclude:
  - .gitignore
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - README.md
encoding:       utf-8
markdown_ext:   md
textile_ext:    textile

# Content handling.
show_drafts:    null
lsi:            false
limit_posts:    0
future:         true
markdown:       kramdown
highlighter:    rouge

# Serving.
#detach:     false
#port:       4000
#host:       127.0.0.1
baseurl:    ""
url:        "http://robot.itcollege.ee"

# Outputting.
permalink:      pretty
paginate:       5
paginate_path:  "news/page:num"
timezone:       UTC

# Posts' and pages' defaults.
defaults:
  -
    # This is the global scope (global defaults). All values here can
    # be overridden in specific post or page.
    scope:
      path: ""
    values:
      # Page title prefix.
      title_prefix: Robotics Club of Estonian IT College
      # Page title.
      title: Robotics Club of Estonian IT College
      # Short description of the page.
      description: 
      # Slogan for the page.
      slogan: Bricked
      # Contact e-mail for pages and posts.
      email: meelis.antoi@itcollege.ee
      # Page/post content license (can contain HTML).
      content_license: Creative Commons
      # Preferred feed standard. Possible values are: atom, rss or null.
      # If set to null then no feed links are present, but feeds can
      # still be accessed directly via /feed/atom or /feed/rss.
      feed: rss
      # Path to icon for feed (Atom standard only).
      feed_icon: null
      # Path to logo for feed (recommended w/h aspect ratio is 2:1).
      feed_logo: null
      # How many posts will be shown in the feed.
      feed_posts_limit: 10
      # Summary length in characters for posts.
      summary_length: 300
      # Various social media and contact methods.
  -
    scope:
      path: ""
      type: posts
    values:
      layout: posts
  -
    scope:
      path: ""
      type: pages
    values:
      layout: pages

gems:
  - jekyll-paginate
